### ISSUE TITLE
Identity Lab 1 Exercise 1 - Adding Web Sign-In : NPM start fails due to invalid parameter in .env file

### ISSUE THREAD

**Issue by michaelwallen** [auth0/identity-102-exercises#44]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Identity Lab 1 Exercise 1 - Adding Web Sign-In : NPM start fails due to invalid .env file
### Reproduction
1. start with .env file from repot
2. Notice the variable: "APP_SESSION_SECRET=LONG_RANDOM_STRING"
3. Start the exercise https://auth0.com/docs/identity-labs/lab-1-web-sign-in/identity-lab-1-exercise-1-walkthrough
4. Get to part where you edit your .env file. Sign in to Auth0 to get the parameters for your tenant and app. 
5. Notice the variable suggests: "COOKIE_SECRET=LONG_RANDOM_STRING"
6. Go to terminal and start npm 
** Expected**
I should be able to copy/paste from the website tutorial into my .env file with no problems running npm. 
**Actual results** 
NPM fails:
`Error: "appSessionSecret" is required
    at module.exports.get (/Users/michael.wallen/Documents/GitHub/identity-102-exercises/identity-102-exercises/lab-01/begin/node_modules/express-openid-connect/lib/config.js:111:11)
    at module.exports (/Users/michael.wallen/Documents/GitHub/identity-102-exercises/identity-102-exercises/lab-01/begin/node_modules/express-openid-connect/middleware/auth.js:25:18)
    at Object.<anonymous> (/Users/michael.wallen/Documents/GitHub/identity-102-exercises/identity-102-exercises/lab-01/begin/server.js:14:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! begin@1.0.0 start: `node server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the begin@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michael.wallen/.npm/_logs/2020-10-29T02_14_36_469Z-debug.log`

Workaround:
Changing the variable to "APP_SESSION_SECRET=LONG_RANDOM_STRING" enables NPM to run. 

Note- This is a great tutorial. Admittedly I am a super noob novice on this stuff and it took me about 3 hours to figure this out. 

### Environment

> Please provide the following:

- **Version of this library used:**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by kajal09** [comment]
I was getting this error instead "TypeError: "secret" is required".
The fix for me was adding "SECRET=LONG_RANDOM_VALUE" to the env file.

**Comment by Kaaelon** [comment]
I experienced the same exception as @kajal09 "TypeError: "secret" is required"

+1 to the fix being updated APP_SESSION_SECRET=LONG_RANDOM_STRING to SECRET=LONG_RANDOM_STRING
